#!/bin/sh
set -e
goal="Improve documentation to include new details"
echo "Plan:"
echo "1. Update the section after 'This will create the following files:' to show only the created files"
echo "2. Enhance the section 'The prompt files will be gitignored.' to include specifics about prompt.yaml, prompt.md, and change.sh"

cat << 'EOF' > docs/usage.md
# Developing External Projects with Junior

## Installation

Install Junior as a development dependency by running the following command:

```
npm add @aijunior/dev --save-dev
```

## Initialization

You can initialize the necessary files in the repository with the command:

```
npx junior-init
```

This will create the following files:

```
.gitignore
prompt/projectSpecifics.md
prompt.yaml
```

The prompt files will be gitignored:
  - `prompt.yaml`, the prompt descriptor filled by the user ([link to descriptor.md](./descriptor.md))
  - `prompt.md`, the generated prompt by Junior
  - `change.sh`, the changeset generated by the language model

### Project Specifics

`prompt/projectSpecifics.md` is used to provide instructions about the codebase that Junior is working on, like preferred tools. It is important to keep this file minimal as it will be included in most prompts, and unnecessary complexity may result in the language model losing track and failing to solve the task.

## Starting Junior

You can start Junior with:

```
npx junior-web
```

For more information about the web interface, please refer to [web.md](./web.md).

EOF

echo "\033[32mDone: $goal\033[0m\n"