#!/bin/sh
set -e
goal="Update documentation with 'Task Interaction Files'"
echo "Plan:"
echo "1. Define the term for the specified files."
echo "2. Update docs/usage.md with the correct term 'Task Interaction Files'."

# Defining the term for the specified files
term="Task Interaction Files"

# Updating the documentation with the new term
cat << 'EOF' > docs/usage.md
# Developing External Projects with Junior

## Installation

Install Junior as a development dependency by running the following command:

```
npm add @aijunior/dev --save-dev
```

## Initialization

You can initialize the necessary files in the repository with the command:

```
npx junior-init
```

This will create the following files:

```
.gitignore
prompt/projectSpecifics.md
prompt.yaml
```

The Task Interaction Files will be gitignored:
  - `prompt.yaml`, the prompt descriptor filled by the user ([link to descriptor.md](./descriptor.md))
  - `prompt.md`, the generated prompt by Junior
  - `change.sh`, the changeset generated by the language model

### Project Specifics

`prompt/projectSpecifics.md` is used to provide instructions about the codebase that Junior is working on, like preferred tools. It is important to keep this file minimal as it will be included in most prompts, and unnecessary complexity may result in the language model losing track and failing to solve the task.

## Starting Junior

You can start Junior with:

```
npx junior-web
```

For more information about the web interface, please refer to [web.md](./web.md).

EOF

echo "\033[32mDone: $goal\033[0m\n"