import { execSync } from 'child_process';
import readline from 'readline';

export async function installBashIfWindows() {
  if (process.platform !== 'win32') {
    console.log("Not on Windows, skipping bash installation check.");
    return;
  }

  try {
    execSync('where bash', { stdio: 'ignore' });
    console.log("Bash found in PATH. No installation needed.");
  } catch (err) {
    console.log("\nWe need Git Bash on Windows to execute changesets generated by the LLM.\n");
    console.log("Bash was not found on this system.\n");

    const rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout
    });

    const question = `
Choose one of the following options to install Git Bash:
  1) winget
  2) choco
  3) Install manually
Enter your choice (1,2 or 3): `;

    rl.question(question, (answer) => {
      rl.close();
      if (answer === '1') {
        try {
          console.log("\nAttempting to install Git (with Bash) via winget...\n");
          execSync('winget install --id Git.Git -e --source winget', { stdio: 'inherit' });
          console.log("\nGit (with Bash) installed successfully via winget!\n");
        } catch (e) {
          console.log("\nFailed to install Git via winget. You may try the other options.\n");
          process.exit(1);
        }
      } else if (answer === '2') {
        try {
          console.log("\nAttempting to install Git (with Bash) via choco...\n");
          execSync('choco install git -y', { stdio: 'inherit' });
          console.log("\nGit (with Bash) installed successfully via choco!\n");
        } catch (e) {
          console.log("\nFailed to install Git via choco. You may try the other options.\n");
          process.exit(1);
        }
      } else {
        console.log("\nPlease install Git for Windows manually from: https://git-scm.com/download/win");
        console.log("Once Git is installed, 'bash' should be in your PATH.\n");
        process.exit(1);
      }
    });
  }
}
